### ISSUE TITLE
Latest version refuses to install

### ISSUE THREAD

**Issue by andrienko** [ym-project/gulp-esbuild#24]
When installing last version (on windows) npm complains:

```
npm ERR! code ETARGET
npm ERR! notarget No matching version found for esbuild@^0.21.5.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in: ...
```

Installing the previous version (`npm install gulp-esbuild@0.11.2`) works just fine.

**Comment by ym-project** [comment]
Hi!

I checked the issue. Can not reproduce. I tried on Linux and on Windows but installation process was ok.

This is `package-lock.json`'s output. As you can see, `esbuild@0.21.5` is here:
![Screenshot_20240711_190312](https://github.com/ym-project/gulp-esbuild/assets/68323354/378be674-761b-4771-b1cb-c77743540f7a)

**Comment by ym-project** [comment]
Maybe it was a problem with your network or npm registry. I don't know :(
