### ISSUE TITLE
gulp-esbuild notify error when run command line in vscode terminal macos

### ISSUE THREAD

**Issue by truong-go2joy** [ym-project/gulp-esbuild#9]
[22:57:07] Error in plugin "gulp-esbuild"
Message:
    Build failed with 1 error:
error: Cannot read directory "../../../../..": operation not permitted
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by ym-project** [comment]
Hi!
Do you have an example to reproduce this problem?

**Comment by mighty9245** [comment]
it seems like an issue on your side. i suspect that you are trying to escape either `/` or `/home/`, not sure what mac will tell you if you do so, but make sure that your working directory allows you to do `../../../../..` (do `pwd` in vscode terminal and image where you will be after `../../../../..` and make sure that you have rights to be there).

**Comment by truong-go2joy** [comment]
> Hi!
> Do you have an example to reproduce this problem?

Hi!
Here is step by step, maby mighty9245 right, but I need to confirm about this my issue, if you're using macOS.

> open vscode and direct to "gulp-esbuild > examples > mjs-gulpfile" project folder
> install package node_modules and "npm run build" at vscode terminal, then you will git that issue.

**Comment by truong-go2joy** [comment]
> it seems like an issue on your side. i suspect that you are trying to escape either `/` or `/home/`, not sure what mac will tell you if you do so, but make sure that your working directory allows you to do `../../../../..` (do `pwd` in vscode terminal and image where you will be after `../../../../..` and make sure that you have rights to be there).

maybe, but my os terminal is work fine. This issue only match in vscode terminal

**Comment by ym-project** [comment]
Unfortunately I don't have macOS devices and I can't check it :(

**Comment by truong-go2joy** [comment]
> Unfortunately I don't have macOS devices and I can't check it :(

never mind bro! I'll research on it, however please give me a suggestion if you have an idea. Cheers

**Comment by ym-project** [comment]
> never mind bro! I'll research on it, however please give me a suggestion if you have an idea. Cheers

I googled and found information about "operation not permitted" for terminal [https://linuxbeast.com/tutorials/fixes/operation-not-permitted-using-terminal-on-visual-studio-code-in-macbook-pro/](https://linuxbeast.com/tutorials/fixes/operation-not-permitted-using-terminal-on-visual-studio-code-in-macbook-pro/).
The author of the article added app to the `Full Disk Access` list.

Maybe you should do the same.

**Comment by truong-go2joy** [comment]
> > never mind bro! I'll research on it, however please give me a suggestion if you have an idea. Cheers
> 
> I googled and found information about "operation not permitted" for terminal https://linuxbeast.com/tutorials/fixes/operation-not-permitted-using-terminal-on-visual-studio-code-in-macbook-pro/.
> The author of the article added app to the `Full Disk Access` list.
> 
> Maybe you should do the same.

Nice! I've fixed it, thks for your support
